import { PeptideDefinition, FreezerStockItem, InjectionSite } from '../types';

export const MASTER_PEPTIDE_DATABASE: PeptideDefinition[] = [
  {
    id: 'retatrutide-10',
    name: 'Retatrutide',
    category: 'GLP-1/GIP/GCG Agonist',
    vialSizeMg: 10,
    unit: 'mg',
    defaultBacWaterMl: 2.0,
    doseRange: { min: 1.0, max: 12.0, step: 0.5 },
    presetDoses: { low: 1.0, standard: 2.0, high: 4.0 },
    halfLifeHours: 144,
    defaultSchedule: 'Mingguan (Weekly)',
    defaultDays: ['Sen'],
    timingTip: 'Injeksi 1x seminggu subkutan. Titrasi dosis setiap 4 minggu.',
    reconInstructions: 'Alirkan 2.0 mL BAC Water perlahan melalui dinding kaca botol.'
  },
  {
    id: 'retatrutide-30',
    name: 'Retatrutide',
    category: 'GLP-1/GIP/GCG Agonist',
    vialSizeMg: 30,
    unit: 'mg',
    defaultBacWaterMl: 3.0,
    doseRange: { min: 2.0, max: 12.0, step: 1.0 },
    presetDoses: { low: 4.0, standard: 8.0, high: 12.0 },
    halfLifeHours: 144,
    defaultSchedule: 'Mingguan (Weekly)',
    defaultDays: ['Sen'],
    timingTip: 'Injeksi 1x seminggu pada fase maintenance dosis tinggi.',
    reconInstructions: 'Alirkan 3.0 mL BAC Water perlahan. Putar lembut hingga larut sempurna.'
  },
  {
    id: 'bpc-157-10',
    name: 'BPC 157',
    category: 'Healing & Gut Support',
    vialSizeMg: 10,
    unit: 'mg',
    defaultBacWaterMl: 2.0,
    doseRange: { min: 0.25, max: 1.0, step: 0.05 },
    presetDoses: { low: 0.25, standard: 0.5, high: 1.0 },
    halfLifeHours: 4,
    defaultSchedule: 'Harian (Daily)',
    defaultDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    timingTip: 'Injeksi harian subkutan di dekat area inflamasi atau perut.',
    reconInstructions: 'Larutkan dengan 2.0 mL BAC Water. Hindari goncangan keras.'
  },
  {
    id: 'cjc-ipa-10',
    name: 'CJC + IPA',
    category: 'GH Secretagogue',
    vialSizeMg: 10,
    unit: 'mg',
    defaultBacWaterMl: 2.0,
    doseRange: { min: 0.1, max: 0.3, step: 0.05 },
    presetDoses: { low: 0.1, standard: 0.2, high: 0.3 },
    halfLifeHours: 2,
    defaultSchedule: 'Harian Malam (Daily Night)',
    defaultDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    timingTip: 'Injeksi malam sebelum tidur saat perut kosong (puasa minimal 2 jam).',
    reconInstructions: 'Larutkan dengan 2.0 mL BAC Water dingin secara perlahan.'
  },
  {
    id: 'ghk-cu-50',
    name: 'GHK-Cu',
    category: 'Tissue Repair / Anti-Aging',
    vialSizeMg: 50,
    unit: 'mg',
    defaultBacWaterMl: 3.0,
    doseRange: { min: 1.0, max: 3.0, step: 0.5 },
    presetDoses: { low: 1.0, standard: 2.0, high: 3.0 },
    halfLifeHours: 1,
    defaultSchedule: 'Harian (Daily)',
    defaultDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    timingTip: 'Gunakan BAC water lebih banyak (3-5 mL) untuk mengurangi rasa perih lokal.',
    reconInstructions: 'Alirkan 3.0 mL BAC Water. Cairan akan berwarna biru pekat.'
  },
  {
    id: 'kisspeptin-10',
    name: 'Kisspeptin',
    category: 'Hormonal Axis Support',
    vialSizeMg: 10,
    unit: 'mg',
    defaultBacWaterMl: 2.0,
    doseRange: { min: 0.1, max: 0.5, step: 0.05 },
    presetDoses: { low: 0.1, standard: 0.25, high: 0.5 },
    halfLifeHours: 0.5,
    defaultSchedule: '2x Seminggu',
    defaultDays: ['Sen', 'Kam'],
    timingTip: 'Injeksi subkutan 2x seminggu untuk modulasi poros hormon LH/FSH.',
    reconInstructions: 'Larutkan dengan 2.0 mL BAC Water secara perlahan.'
  },
  {
    id: 'lc526-10',
    name: 'LC526',
    category: 'Fat Metabolism & Liver',
    vialSizeMg: 10,
    unit: 'mL',
    defaultBacWaterMl: 0,
    doseRange: { min: 0.5, max: 2.0, step: 0.25 },
    presetDoses: { low: 0.5, standard: 1.0, high: 2.0 },
    halfLifeHours: 8,
    defaultSchedule: '2-3x Seminggu',
    defaultDays: ['Sen', 'Rab', 'Jum'],
    timingTip: 'Cairan steril siap pakai. Injeksi intramuskular atau subkutan perlahan.',
    reconInstructions: 'Vial bentuk cair siap pakai, tidak memerlukan rekonstitusi air BAC.'
  },
  {
    id: 'mots-c-20',
    name: 'MOTS-c',
    category: 'Mitochondrial Energy',
    vialSizeMg: 20,
    unit: 'mg',
    defaultBacWaterMl: 2.0,
    doseRange: { min: 5.0, max: 10.0, step: 1.0 },
    presetDoses: { low: 5.0, standard: 7.5, high: 10.0 },
    halfLifeHours: 4,
    defaultSchedule: '3x Seminggu',
    defaultDays: ['Sen', 'Rab', 'Jum'],
    timingTip: 'Suntikkan di pagi hari sebelum berolahraga untuk metabolisme optimal.',
    reconInstructions: 'Alirkan 2.0 mL BAC Water perlahan, jangan dikocok.'
  },
  {
    id: 'glutathione-1200',
    name: 'Glutathione (GSH)',
    category: 'Master Antioxidant & Liver Detox',
    vialSizeMg: 1200,
    unit: 'mg',
    defaultBacWaterMl: 4.0,
    doseRange: { min: 200, max: 600, step: 50 },
    presetDoses: { low: 200, standard: 400, high: 600 },
    halfLifeHours: 0.5,
    defaultSchedule: '2x Seminggu',
    defaultDays: ['Sen', 'Kam'],
    timingTip: 'Pagi hari atau pasca paparan toksin tinggi. Larutkan dengan air lebih banyak.',
    reconInstructions: 'Larutkan dengan 4.0 mL BAC Water agar tidak perih saat disuntik.'
  },
  {
    id: 'peg-mgf-2',
    name: 'PEG-MGF',
    category: 'Muscle Recovery & Stem Cell Activation',
    vialSizeMg: 2,
    unit: 'mg',
    defaultBacWaterMl: 2.0,
    doseRange: { min: 0.2, max: 0.4, step: 0.05 },
    presetDoses: { low: 0.2, standard: 0.3, high: 0.4 },
    halfLifeHours: 60,
    defaultSchedule: '2x Seminggu',
    defaultDays: ['Sen', 'Kam'],
    timingTip: 'Suntikkan 1-2 jam pasca latihan beban atau saat hari pemulihan.',
    reconInstructions: 'Alirkan 2.0 mL BAC Water dingin perlahan via dinding botol.'
  },
  {
    id: 'ace-031-1',
    name: 'ACE-031',
    category: 'Myostatin Inhibitor & Anabolic Axis',
    vialSizeMg: 1,
    unit: 'mg',
    defaultBacWaterMl: 1.0,
    doseRange: { min: 0.5, max: 3.0, step: 0.5 },
    presetDoses: { low: 1.0, standard: 2.0, high: 3.0 },
    halfLifeHours: 288,
    defaultSchedule: 'Mingguan (Weekly)',
    defaultDays: ['Sen'],
    timingTip: 'Injeksi 1x setiap 10-14 hari sekali dalam siklus pendek 2-4 minggu.',
    reconInstructions: 'Protein rapuh. Larutkan 1.0 mL BAC Water perlahan tanpa busa.'
  }
];

export const INITIAL_FREEZER_ITEMS: FreezerStockItem[] = [
  {
    id: 'freezer-bpc-157',
    name: 'BPC 157',
    vialSizeMg: 10,
    unit: 'mg',
    category: 'Healing & Gut Support',
    freezerStock: 10,
    bacWaterMl: 2.0,
    defaultDose: 0.5,
    presetDoses: { low: 0.25, standard: 0.5, high: 1.0 },
    schedule: 'Harian (Daily)',
    injectionDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    penClicksPerMl: 100,
    halfLifeHours: 4
  },
  {
    id: 'freezer-cjc-ipa',
    name: 'CJC + IPA',
    vialSizeMg: 10,
    unit: 'mg',
    category: 'Peptide Protocol',
    freezerStock: 10,
    bacWaterMl: 2.0,
    defaultDose: 0.2,
    presetDoses: { low: 0.1, standard: 0.2, high: 0.3 },
    schedule: 'Harian Malam (Daily Night)',
    injectionDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    penClicksPerMl: 100,
    halfLifeHours: 2
  },
  {
    id: 'freezer-ghk-cu',
    name: 'GHK-Cu',
    vialSizeMg: 50,
    unit: 'mg',
    category: 'Tissue Repair / Anti-Aging',
    freezerStock: 9,
    bacWaterMl: 3.0,
    defaultDose: 2.0,
    presetDoses: { low: 1.0, standard: 2.0, high: 3.0 },
    schedule: 'Harian (Daily)',
    injectionDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    penClicksPerMl: 100,
    halfLifeHours: 1
  },
  {
    id: 'freezer-kisspeptin',
    name: 'Kisspeptin',
    vialSizeMg: 10,
    unit: 'mg',
    category: 'Hormonal Axis Support',
    freezerStock: 10,
    bacWaterMl: 2.0,
    defaultDose: 0.25,
    presetDoses: { low: 0.1, standard: 0.25, high: 0.5 },
    schedule: '2x Seminggu',
    injectionDays: ['Sen', 'Kam'],
    penClicksPerMl: 100,
    halfLifeHours: 0.5
  },
  {
    id: 'freezer-lc526',
    name: 'LC526',
    vialSizeMg: 10,
    unit: 'mL',
    category: 'Fat Metabolism & Liver',
    freezerStock: 10,
    bacWaterMl: 0,
    defaultDose: 1.0,
    presetDoses: { low: 0.5, standard: 1.0, high: 2.0 },
    schedule: '2-3x Seminggu',
    injectionDays: ['Sen', 'Rab', 'Jum'],
    penClicksPerMl: 100,
    halfLifeHours: 8
  },
  {
    id: 'freezer-mots-c',
    name: 'MOTS-c',
    vialSizeMg: 20,
    unit: 'mg',
    category: 'Mitochondrial Energy',
    freezerStock: 10,
    bacWaterMl: 2.0,
    defaultDose: 5.0,
    presetDoses: { low: 5.0, standard: 7.5, high: 10.0 },
    schedule: '3x Seminggu',
    injectionDays: ['Sen', 'Rab', 'Jum'],
    penClicksPerMl: 100,
    halfLifeHours: 4
  },
  {
    id: 'freezer-retatrutide-10',
    name: 'Retatrutide',
    vialSizeMg: 10,
    unit: 'mg',
    category: 'GLP-1/GIP/GCG',
    freezerStock: 10,
    bacWaterMl: 2.0,
    defaultDose: 2.0,
    presetDoses: { low: 1.0, standard: 2.0, high: 4.0 },
    schedule: 'Mingguan (Weekly)',
    injectionDays: ['Sen'],
    penClicksPerMl: 100,
    halfLifeHours: 144
  },
  {
    id: 'freezer-retatrutide-30',
    name: 'Retatrutide',
    vialSizeMg: 30,
    unit: 'mg',
    category: 'GLP-1/GIP/GCG',
    freezerStock: 10,
    bacWaterMl: 3.0,
    defaultDose: 4.0,
    presetDoses: { low: 2.0, standard: 4.0, high: 8.0 },
    schedule: 'Mingguan (Weekly)',
    injectionDays: ['Sen'],
    penClicksPerMl: 100,
    halfLifeHours: 144
  }
];

export const INJECTION_SITES: InjectionSite[] = [
  { id: 'TL', code: 'TL', name: 'Kiri Atas (TL)', desc: 'Perut kiri atas (2-3 cm dari pusar)', side: 'Kiri', cx: 205, cy: 115 },
  { id: 'TR', code: 'TR', name: 'Kanan Atas (TR)', desc: 'Perut kanan atas (2-3 cm dari pusar)', side: 'Kanan', cx: 115, cy: 115 },
  { id: 'BR', code: 'BR', name: 'Kanan Bawah (BR)', desc: 'Perut kanan bawah (2-3 cm dari pusar)', side: 'Kanan', cx: 115, cy: 205 },
  { id: 'BL', code: 'BL', name: 'Kiri Bawah (BL)', desc: 'Perut kiri bawah (2-3 cm dari pusar)', side: 'Kiri', cx: 205, cy: 205 }
];
