import { FreezerItem } from '../store/useBioStackStore';

// Database template peptida — field name sama persis dengan FreezerItem
export const DEFAULT_PEPTIDES: FreezerItem[] = [
  {
    id: 'pep-reta-1',
    name: 'Retatrutide',
    category: 'GLP-1 / GIP / GCG Tri-Agonist',
    vialSize: 10,
    unit: 'mg',
    quantity: 10,
    defaultBacWater: 2.0,
    targetDose: 2.0,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 6.0,
    maxFridgeDays: 56,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-tirz-1',
    name: 'Tirzepatide',
    category: 'GLP-1 / GIP Dual Agonist',
    vialSize: 10,
    unit: 'mg',
    quantity: 10,
    defaultBacWater: 2.0,
    targetDose: 2.5,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 5.0,
    maxFridgeDays: 56,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-sema-1',
    name: 'Semaglutide',
    category: 'GLP-1 Receptor Agonist',
    vialSize: 5,
    unit: 'mg',
    quantity: 8,
    defaultBacWater: 2.0,
    targetDose: 0.5,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 7.0,
    maxFridgeDays: 56,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-cagri-1',
    name: 'Cagrilintide',
    category: 'Amylin Analogue / Satiety',
    vialSize: 5,
    unit: 'mg',
    quantity: 8,
    defaultBacWater: 2.0,
    targetDose: 0.3,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 7.0,
    maxFridgeDays: 56,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-ghk-1',
    name: 'GHK-Cu',
    category: 'Tissue Repair & Collagen',
    vialSize: 50,
    unit: 'mg',
    quantity: 10,
    defaultBacWater: 3.0,
    targetDose: 2.0,
    frequency: 'daily',
    frequencyLabel: 'Harian (Daily)',
    halfLifeDays: 0.5,
    maxFridgeDays: 28,
    activeDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-motsc-1',
    name: 'MOTS-c',
    category: 'Mitochondrial Energy',
    vialSize: 20,
    unit: 'mg',
    quantity: 10,
    defaultBacWater: 2.0,
    targetDose: 5.0,
    frequency: '3x_week',
    frequencyLabel: '3x Seminggu',
    halfLifeDays: 1.0,
    maxFridgeDays: 28,
    activeDays: ['Sen', 'Rab', 'Jum'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-lc526-1',
    name: 'LC526',
    category: 'Fat Metabolism & Liver',
    vialSize: 10,
    unit: 'mL',
    quantity: 10,
    defaultBacWater: 0,
    targetDose: 0.2,
    frequency: 'daily',
    frequencyLabel: 'Harian (Daily)',
    halfLifeDays: 1.0,
    maxFridgeDays: 60,
    activeDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    injectionTime: '08:00',
  },
  {
    id: 'pep-kiss-1',
    name: 'Kisspeptin',
    category: 'Hormonal Axis Support',
    vialSize: 10,
    unit: 'mg',
    quantity: 10,
    defaultBacWater: 2.0,
    targetDose: 0.2,
    frequency: '3x_week',
    frequencyLabel: '3x Seminggu',
    halfLifeDays: 1.0,
    maxFridgeDays: 28,
    activeDays: ['Sen', 'Rab', 'Jum'],
    injectionTime: '17:15',
  },
];
